NumPy Assignment Questions

Data Types & Attributes

1. Create a NumPy array arr of integers from 0 to 5 and print its data type.

In [8]:
import numpy as np
arr1 = np.array(list(map(int, input("Enter integers separated by space (0–5): ").split())))
print(arr1.dtype) 

Enter integers separated by space (0–5):  0 1 2 3 4 5


int32


2. Given a NumPy array arr, check if its data type is float64.

In [11]:
arr2 = np.array(list(map(float, input("Enter float numbers: ").split())))
print(arr2.dtype == np.float64)

Enter float numbers:  1.1 2.2 3.3


True


3. Create a NumPy array arr with a data type of complex128 containing three
complex numbers.

In [14]:
arr3 = np.array([complex(x) for x in input("Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j): ").split()], dtype=np.complex128)
print(arr3)
print(arr3.dtype)

Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j):  1+2j 3+4j 5+6j


[1.+2.j 3.+4.j 5.+6.j]
complex128


4. Convert an existing NumPy array arr of integers to float32 data type.

In [16]:
arr4 = np.array(list(map(int, input("Enter integers: ").split())))
arr4 = arr4.astype(np.float32)
print(arr4)
print(arr4.dtype)

Enter integers:  10 20 30


[10. 20. 30.]
float32


5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce
decimal precision.

In [22]:
arr5 = np.array(list(map(float, input("Enter float64 numbers: ").split())), dtype=np.float64)
arr5 = arr5.astype(np.float32)
print(arr5)

Enter float64 numbers:  1.123456789 2.987654321


[1.1234568 2.9876542]


6. Write a function array_attributes that takes a NumPy array as input and returns
its shape, size, and data type.

In [33]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)])
print(array_attributes(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  31 21


((2, 2), 4, dtype('int32'))


7. Create a function array_dimension that returns the dimensionality of a NumPy
array.

In [35]:
def array_dimension(arr):
    return arr.ndim
arr = np.array(eval(input("Enter a nested list (e.g., [[1,2],[3,4]]): ")))
print(array_dimension(arr))

Enter a nested list (e.g., [[1,2],[3,4]]):  [[1,2],[3,4]]


2


8. Design a function item_size_info that returns the item size and total size in bytes
of a NumPy array.

In [37]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
arr = np.array(list(map(int, input("Enter integers: ").split())), dtype=np.int32)
print(item_size_info(arr))

Enter integers:  10 20 30


(4, 12)


9. Create a function array_strides that returns the strides of the given NumPy array.

In [39]:
def array_strides(arr):
    return arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)], dtype=np.int32)
print(array_strides(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  3 4


(8, 4)


10. Design a function shape_stride_relationship that returns the shape and
strides of the given array.

In [41]:
 def shape_stride_relationship(arr):
    return arr.shape, arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.ones((r, c), dtype=np.float64)
print(shape_stride_relationship(arr))

Enter number of rows:  3
Enter number of columns:  3


((3, 3), (24, 8))


Array Creation

11. Create a function create_zeros_array(n) to return a NumPy array of zeros with
n elements.

In [57]:
def create_zeros_array(n):
    return np.zeros(n)
n = int(input("Enter number of elements: "))
print(create_zeros_array(n))

Enter number of elements:  5


[0. 0. 0. 0. 0.]


12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled
with ones.

In [55]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))
print(create_ones_matrix(rows, cols))

Enter number of rows:  2
Enter number of columns:  2


[[1. 1.]
 [1. 1.]]


13. Write a function generate_range_array(start, stop, step) to create a
ranged NumPy array.

In [59]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = int(input("Enter start: "))
stop = int(input("Enter stop: "))
step = int(input("Enter step: "))
print(generate_range_array(start, stop, step))

Enter start:  2
Enter stop:  10
Enter step:  2


[2 4 6 8]


14. Design a function generate_linear_space(start, stop, num) for equally
spaced values.

In [65]:
def generate_linear_space():
    start = float(input("Enter the start value: "))
    stop = float(input("Enter the stop value: "))
    num = int(input("Enter the number of values: "))
    result = np.linspace(start, stop, num)
    print("Linear Space:", result)
generate_linear_space()

Enter the start value:  2
Enter the stop value:  15
Enter the number of values:  5


Linear Space: [ 2.    5.25  8.5  11.75 15.  ]


15. Create a function create_identity_matrix(n) using numpy.eye.

In [77]:
def create_identity_matrix(n):
    return np.eye(n)
n = int(input("Enter size of identity matrix: "))
print(create_identity_matrix(n))

Enter size of identity matrix:  4


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Write a function that converts a Python list into a NumPy array.

In [81]:
def convert_list_to_array(lst):
    return np.array(lst)
lst = eval(input("Enter a Python list (e.g., [1, 2, 3, 4]): "))
print(convert_list_to_array(lst))

Enter a Python list (e.g., [1, 2, 3, 4]):  [10, 20, 30]


[10 20 30]


17. Create a NumPy array and use numpy.view() to create a new view with the same
data.

In [83]:
arr = np.array(list(map(int, input("Enter array elements: ").split())))
view_arr = arr.view()
print("Original array:", arr)
print("View array:", view_arr)

Enter array elements:  1 2 3 4 5


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]


Concatenation and Stacking

18. Write a function to concatenate two NumPy arrays along a specified axis.

In [8]:
def concatenate_arrays():
    arr1 = input("Enter elements of first array (space-separated): ")
    arr2 = input("Enter elements of second array (space-separated): ")
    axis = int(input("Enter axis (0 for vertical, 1 for horizontal): "))
    a1 = np.array([int(x) for x in arr1.split()])
    a2 = np.array([int(x) for x in arr2.split()])
    if axis == 1:
        a1 = a1.reshape(1, -1)
        a2 = a2.reshape(1, -1)
    result = np.concatenate((a1, a2), axis=axis)
    print("Concatenated Array:\n", result)

19. Concatenate two arrays with different shapes horizontally using
numpy.concatenate.

In [16]:
import numpy as np
rows = int(input("Enter number of rows for array a: "))
a = []
print("Enter elements for array a (1 element per row):")
for _ in range(rows):
    a.append([int(input())])
a = np.array(a)
cols = int(input("Enter number of columns for array b: "))
b = list(map(int, input(f"Enter {cols} elements for 1 row of array b: ").split()))
b = np.array([b])
b_reshaped = np.repeat(b, rows, axis=0)
result = np.concatenate((a, b_reshaped), axis=1)
print("Concatenated Array:\n", result)

Enter number of rows for array a:  3


Enter elements for array a (1 element per row):


 1
 2
 3
Enter number of columns for array b:  2
Enter 2 elements for 1 row of array b:  4 5


Concatenated Array:
 [[1 4 5]
 [2 4 5]
 [3 4 5]]



20. Vertically stack multiple arrays from a list using numpy.vstack.

In [20]:
n = int(input("Enter number of arrays to stack: "))
arrays = []
for i in range(n):
    arr = list(map(int, input(f"Enter elements of array {i+1} (space-separated): ").split()))
    arrays.append(np.array(arr))
result = np.vstack(arrays)
print("\nOutput:")
print(result)

Enter number of arrays to stack:  3
Enter elements of array 1 (space-separated):  1 2
Enter elements of array 2 (space-separated):  2 3
Enter elements of array 3 (space-separated):  3 4



Output:
[[1 2]
 [2 3]
 [3 4]]


Array Generation

21. Write a function to generate an array of integers within a specified range (inclusive)
with a step.

In [31]:
start = int(input("Enter start value: "))
stop = int(input("Enter stop value (inclusive): "))
step = int(input("Enter step value: "))
result = np.arange(start, stop + 1, step)
print("\nOutput:")
print(result)

Enter start value:  2
Enter stop value (inclusive):  10
Enter step value:  2



Output:
[ 2  4  6  8 10]


22. Generate 10 equally spaced values between 0 and 1 using NumPy.

In [29]:
result = np.linspace(0, 1, 10)
print("\nOutput:")
print(result)


Output:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Create 5 logarithmically spaced values between 1 and 1000.

In [33]:
result = np.logspace(0, 3, 5)
print("\nOutput:")
print(result)


Output:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Pandas + NumPy

24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of
random integers (1-100).

In [38]:
import pandas as pd
array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
print("\nOutput:")
print(df)


Output:
    A   B   C
0  60   6  18
1  87  32  27
2  97  75   9
3  11  97  89
4  97  28  34


25. Write a function to replace all negative values in a specific column with zeros using
NumPy.

In [40]:
data = {
    'A': [5, -3, 7, -1],
    'B': [2, -6, -4, 9]
}
df = pd.DataFrame(data)
col = input("Enter column name to replace negatives with 0: ")
arr = df[col].values
arr[arr < 0] = 0
df[col] = arr
print("\nOutput:")
print(df)

Enter column name to replace negatives with 0:  B



Output:
   A  B
0  5  2
1 -3  0
2  7  0
3 -1  9


Indexing and Slicing

26. Access the 3rd element from the given NumPy array.

In [50]:
arr = np.array(list(map(int, input("Enter elements of the array (space-separated): ").split())))
print("\nOutput:")
print(arr[2])

Enter elements of the array (space-separated):  10 20 30 40 50



Output:
30


27. Retrieve the element at index (1, 2) from a 2D array.

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOutput:")
print(arr[1, 2])


Output:
6



28. Extract elements greater than 5 using boolean indexing.

In [58]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
print("\nOutput:")
print(arr[arr > 5])

Enter array elements (space-separated):  3 7 5 1 2



Output:
[7]



29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.

In [60]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
print("\nOutput:")
print(arr[2:6])

Enter array elements (space-separated):  10 12 14 56 45



Output:
[14 56 45]



30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOutput:")
print(arr[0:2, 1:3])


Output:
[[2 3]
 [5 6]]


Advanced Indexing


31. Extract elements based on indices from a 2D array.

In [72]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
indices = [0, 2]
print("\nOutput:")
print(arr[indices])


Output:
[[10 20 30]
 [70 80 90]]



32. Filter elements greater than a threshold using boolean indexing.

In [74]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
threshold = int(input("Enter threshold: "))
print("\nOutput:")
print(arr[arr > threshold])

Enter array elements (space-separated):  1 3 5 7 9
Enter threshold:  5



Output:
[7 9]



33. Extract specific elements from a 3D array using separate index arrays.

In [76]:
arr = np.arange(27).reshape(3, 3, 3)
i = np.array([0, 1, 2])
j = np.array([1, 1, 1])
k = np.array([2, 2, 2])
print("\nOutput:")
print(arr[i, j, k])


Output:
[ 5 14 23]



34. Return elements satisfying two boolean conditions.

In [78]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
print("\nOutput:")
print(arr[(arr > 5) & (arr < 10)])

Enter array elements (space-separated):  2 4 6 8 10 12



Output:
[6 8]



35. Extract elements from a 2D array using separate row and column index arrays.

In [80]:
arr = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 2])
print("\nOutput:")
print(arr[rows, cols])


Output:
[12 21 33]


Broadcasting


36. Add scalar 5 to every element of an array using broadcasting.

In [90]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
result = arr + 5
print("\nOutput:")
print(result)

Enter array elements (space-separated):  1 2 3 4 5



Output:
[ 6  7  8  9 10]



37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.

In [92]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
B = np.array([[1], [2], [3]])
result = A * B
print("\nOutput:")
print(result)


Output:
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]



38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.

In [94]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])
B = np.array([[100, 200, 300]])
result = A + B
print("\nOutput:")
print(result)


Output:
[[101 202 303]
 [104 205 306]
 [107 208 309]
 [110 211 312]]



39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.

In [96]:
A = np.array([[1], [2], [3]])
B = np.array([[10, 20, 30]])
result = A + B
print("\nOutput:")
print(result)


Output:
[[11 21 31]
 [12 22 32]
 [13 23 33]]



40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2)
arrays.


In [98]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 2],
              [3, 4]])
try:
    result = A * B
except ValueError as e:
    result = str(e)
print("\nOutput:")
print(result)


Output:
operands could not be broadcast together with shapes (2,3) (2,2) 


Aggregations and Statistics

41. Calculate column-wise mean of a 2D array.

In [114]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.mean(arr, axis=0)
print("\nOutput:")
print(result)


Output:
[4. 5. 6.]



42. Find maximum value in each row.

In [126]:
arr = np.array([[3, 8, 1], [6, 7, 2], [4, 5, 9]])
result = np.max(arr, axis=1)
print("\nOutput:")
print(result)


Output:
[8 7 9]



43. Find indices of maximum values in each column.

In [124]:
arr = np.array([[10, 25, 13], [22, 14, 19], [5, 30, 7]])
result = np.argmax(arr, axis=0)
print("\nOutput:")
print(result)


Output:
[1 2 1]



44. Apply a custom function to compute moving sum along rows.

In [122]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
k = int(input("Enter window size: "))
result = np.array([np.convolve(row, np.ones(k, dtype=int), 'valid') for row in arr])
print("\nOutput:")
print(result)

Enter window size:  2



Output:
[[ 3  5  7]
 [11 13 15]]



45. Check if all elements in each column are even.

In [128]:
arr = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
result = np.all(arr % 2 == 0, axis=0)
print("\nOutput:")
print(result)


Output:
[ True  True  True]


Reshaping and Flattening

46. Reshape a given array into dimensions m x n.

In [130]:
arr = np.array(list(map(int, input("Enter elements of array (space-separated): ").split())))
m = int(input("Enter number of rows: "))
n = int(input("Enter number of columns: "))
result = arr.reshape(m, n)
print("\nOutput:")
print(result)

Enter elements of array (space-separated):  1 2 3 4 5 6
Enter number of rows:  2 
Enter number of columns:  3



Output:
[[1 2 3]
 [4 5 6]]


47. Return a flattened version of a given matrix.

In [132]:
arr = np.array([[1, 2], [3, 4]])
result = arr.flatten()
print("\nOutput:")
print(result)


Output:
[1 2 3 4]



48. Concatenate two arrays along a specified axis.

In [136]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
axis = int(input("Enter axis to concatenate on (0 or 1): "))
result = np.concatenate((a, b), axis=axis)
print("\nOutput:")
print(result)

Enter axis to concatenate on (0 or 1):  1



Output:
[[1 2 5 6]
 [3 4 7 8]]



49. Split an array into sub-arrays along a specified axis.

In [138]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
axis = int(input("Enter axis to split on (0 or 1): "))
result = np.split(arr, 2, axis=axis)
print("\nOutput:")
for r in result:
    print(r)

Enter axis to split on (0 or 1):  0



Output:
[[10 20 30 40]]
[[50 60 70 80]]



50. Insert and delete elements at specified indices from an array.


In [140]:
arr = np.array([1, 2, 3, 4, 5])
insert_val = int(input("Enter value to insert: "))
insert_index = int(input("Enter index to insert at: "))
delete_index = int(input("Enter index to delete: "))
arr = np.insert(arr, insert_index, insert_val)
arr = np.delete(arr, delete_index)
print("\nOutput:")
print(arr)

Enter value to insert:  99
Enter index to insert at:  2
Enter index to delete:  4



Output:
[ 1  2 99  3  5]


Element-wise Operations


51. Perform element-wise addition between two arrays.

In [154]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print("\nOutput:")
print(result)


Output:
[5 7 9]



52. Perform element-wise subtraction: subtract arr2 from arr1.

In [156]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print("\nOutput:")
print(result)


Output:
[ 9 18 27]



53. Perform element-wise multiplication.

In [158]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([5, 6, 7])
result = arr1 * arr2
print("\nOutput:")
print(result)


Output:
[10 18 28]



54. Divide elements of arr1 by arr2 element-wise.

In [160]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])
result = arr1 / arr2
print("\nOutput:")
print(result)


Output:
[5. 5. 6.]


55. Perform element-wise exponentiation: arr1 ** arr2.

In [162]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 2, 1])
result = arr1 ** arr2
print("\nOutput:")
print(result)


Output:
[8 9 4]



String Operations


56. Count occurrences of a substring in a string array.

In [164]:
arr = np.array(["apple pie", "banana pie", "pie crust"])
result = np.char.count(arr, "pie")
print("\nOutput:")
print(result)


Output:
[1 1 1]



57. Extract uppercase characters from a string array.

In [166]:
arr = np.array(["HeLLo", "WOrLD", "PyThOn"])
result = np.char.array([ ''.join([ch for ch in s if ch.isupper()]) for s in arr ])
print("\nOutput:")
print(result)


Output:
['HLL' 'WOLD' 'PTO']



58. Replace substring occurrences with another string in a string array.

In [168]:
arr = np.array(["hello world", "world peace", "brave new world"])
result = np.char.replace(arr, "world", "universe")
print("\nOutput:")
print(result)


Output:
['hello universe' 'universe peace' 'brave new universe']



59. Concatenate strings in a NumPy array element-wise.

In [170]:
arr1 = np.array(["good ", "great ", "awesome "])
arr2 = np.array(["morning", "job", "day"])
result = np.char.add(arr1, arr2)
print("\nOutput:")
print(result)


Output:
['good morning' 'great job' 'awesome day']



60. Find the length of the longest string in a string array.


In [172]:
arr = np.array(["short", "longeststringhere", "medium"])
result = np.max(np.char.str_len(arr))
print("\nOutput:")
print(result)


Output:
17


Descriptive Statistics

61. Generate 100 random integers (1–1000) and compute mean, median, variance, and
std deviation.


In [190]:
arr = np.random.randint(1, 1001, 100)
mean = np.mean(arr)
median = np.median(arr)
var = np.var(arr)
std = np.std(arr)
print("\nOutput:")
print("Mean:", mean)
print("Median:", median)
print("Variance:", var)
print("Std Deviation:", std)


Output:
Mean: 580.76
Median: 642.5
Variance: 88458.78239999998
Std Deviation: 297.4202118215909



62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.

In [192]:
arr = np.random.randint(1, 101, 50)
p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)
print("\nOutput:")
print("25th Percentile:", p25)
print("75th Percentile:", p75)


Output:
25th Percentile: 29.5
75th Percentile: 87.5



63. Compute correlation coefficient between two arrays using np.corrcoef.

In [194]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 60])
result = np.corrcoef(x, y)
print("\nOutput:")
print(result)


Output:
[[1.         0.99589321]
 [0.99589321 1.        ]]



64. Perform matrix multiplication using np.dot.

In [196]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("\nOutput:")
print(result)


Output:
[[19 22]
 [43 50]]



65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50
integers.

In [198]:
arr = np.random.randint(1, 101, 50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
print("\nOutput:")
print("10th:", p10)
print("50th:", p50)
print("90th:", p90)
print("Q1:", q1)
print("Q3:", q3)


Output:
10th: 10.9
50th: 50.5
90th: 90.0
Q1: 33.25
Q3: 76.0



Search and Sort


66. Find index of a specific element in an array.

In [200]:
arr = np.array([10, 20, 30, 40, 50])
val = int(input("Enter value to find index of: "))
result = np.where(arr == val)[0]
print("\nOutput:")
print(result)

Enter value to find index of:  40



Output:
[3]



67. Sort a random array in ascending order.

In [202]:
arr = np.random.randint(1, 101, 10)
sorted_arr = np.sort(arr)
print("\nOutput:")
print(sorted_arr)


Output:
[14 14 45 57 60 71 76 77 80 81]



68. Filter elements greater than 20.

In [204]:
arr = np.array([10, 25, 30, 5, 50])
result = arr[arr > 20]
print("\nOutput:")
print(result)


Output:
[25 30 50]



69. Filter elements divisible by 3.

In [206]:
arr = np.array([9, 10, 12, 14, 15])
result = arr[arr % 3 == 0]
print("\nOutput:")
print(result)


Output:
[ 9 12 15]



70. Filter elements between 20 and 40 (inclusive).

In [208]:
arr = np.array([15, 20, 25, 30, 40, 45])
result = arr[(arr >= 20) & (arr <= 40)]
print("\nOutput:")
print(result)


Output:
[20 25 30 40]



Byte Order & Swapping


71. Check byte order of a NumPy array using dtype.byteorder.

In [212]:
arr = np.array([1, 2, 3], dtype=np.int16)
print("\nOutput:")
print(arr.dtype.byteorder)


Output:
=



72. Perform in-place byte swapping using byteswap().

In [218]:
arr = np.array([1, 256, 512], dtype=np.int16)
arr.byteswap(True)
print("\nOutput:")
print(arr)


Output:
[256   1   2]
